export enum ObjectSubType {
    STATIC = 'STATIC',
    MINING = 'MINING',
    MILITARY = 'MILITARY',
    SCIENCE = 'SCIENCE',
    PRODUCTION = 'PRODUCTION',
    ASYLUM = 'ASYLUM',
    DYNAMIC = 'DYNAMIC'
}