export enum NotificationType {
    INVITED_TO_ROOM = 'INVITED_TO_ROOM',
    EDITED_ROOM_TITLE = 'EDITED_ROOM_TITLE',
    KICK_USER_FROM_ROOM = 'KICK_USER_FROM_ROOM',
    ROOM_UPDATED = 'ROOM_UPDATED',
    BET_OVERBID = 'BET_OVERBID',
    INSTANT_PURCHASE = 'INSTANT_PURCHASE',
    MONEY_UPDATED = 'MONEY_UPDATED',
    LEAVE_ROOM = 'LEAVE_ROOM',
    MESSAGE_TO_SCREEN = 'MESSAGE_TO_SCREEN',
    EXCHANGE_INVITATION = 'EXCHANGE_INVITATION',
    EXCHANGE_INVITATION_REJECTED = 'EXCHANGE_INVITATION_REJECTED',
    EXCHANGE_CREATED = 'EXCHANGE_CREATED',
    EXCHANGE_COMPLETED = 'EXCHANGE_COMPLETED',
    LEAVE_EXCHANGE = 'LEAVE_EXCHANGE',
    OFFER_CREATED = 'OFFER_CREATED',
    OFFER_UPDATED = 'OFFER_UPDATED',
    CANNOT_ATTACH_TO_ORBIT = 'CANNOT_ATTACH_TO_ORBIT'
}